# Reinforcement learning

In [1]:
import gym

In [2]:
gym.envs.registry.all()

dict_values([EnvSpec(Copy-v0), EnvSpec(RepeatCopy-v0), EnvSpec(ReversedAddition-v0), EnvSpec(ReversedAddition3-v0), EnvSpec(DuplicatedInput-v0), EnvSpec(Reverse-v0), EnvSpec(CartPole-v0), EnvSpec(CartPole-v1), EnvSpec(MountainCar-v0), EnvSpec(MountainCarContinuous-v0), EnvSpec(Pendulum-v0), EnvSpec(Acrobot-v1), EnvSpec(LunarLander-v2), EnvSpec(LunarLanderContinuous-v2), EnvSpec(BipedalWalker-v3), EnvSpec(BipedalWalkerHardcore-v3), EnvSpec(CarRacing-v0), EnvSpec(Blackjack-v0), EnvSpec(KellyCoinflip-v0), EnvSpec(KellyCoinflipGeneralized-v0), EnvSpec(FrozenLake-v0), EnvSpec(FrozenLake8x8-v0), EnvSpec(CliffWalking-v0), EnvSpec(NChain-v0), EnvSpec(Roulette-v0), EnvSpec(Taxi-v3), EnvSpec(GuessingGame-v0), EnvSpec(HotterColder-v0), EnvSpec(Reacher-v2), EnvSpec(Pusher-v2), EnvSpec(Thrower-v2), EnvSpec(Striker-v2), EnvSpec(InvertedPendulum-v2), EnvSpec(InvertedDoublePendulum-v2), EnvSpec(HalfCheetah-v2), EnvSpec(HalfCheetah-v3), EnvSpec(Hopper-v2), EnvSpec(Hopper-v3), EnvSpec(Swimmer-v2), EnvSp

In [3]:
env = gym.make('CartPole-v1')

In [10]:
# init environment of cartpole
obs = env.reset()

In [5]:
env.class_name()

'TimeLimit'

In [7]:
## Test one step
obs, reward, done, info = env.step(1)

In [11]:
print(obs)
print(reward)
print(done)
print(info)

[-0.02085998  0.40640211 -0.03702923 -0.66289499]
1.0
False
{}


In [6]:
def update_scene(num, frames, patch):
    patch.set_data(frames[num])
    return patch,

def plot_animation(frames, repeat=False, interval=40):
    fig = plt.figure()
    patch = plt.imshow(frames[0])
    plt.axis('off')
    anim = animation.FuncAnimation(
        fig, update_scene, fargs=(frames, patch),
        frames=len(frames), repeat=repeat, interval=interval)
    plt.close()
    return anim

## Create simple NN model to predict the action

In [7]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
# To get smooth animations
import matplotlib.animation as animation
mpl.rc('animation', html='jshtml')

In [48]:
keras.backend.clear_session()
model = keras.models.Sequential([
    keras.layers.Dense(10, activation = 'relu', input_shape=[4]),
    keras.layers.Dense(1, activation='sigmoid')
])

In [11]:
model(tf.expand_dims(obs, axis=0))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.49641845]], dtype=float32)>

In [49]:
model.get_weights()

[array([[ 0.07343501,  0.40278435,  0.40317416, -0.07176459,  0.3497281 ,
          0.10372061,  0.20479   , -0.39860633,  0.52469456,  0.52972054],
        [-0.6323479 , -0.5438434 ,  0.359944  ,  0.42467833, -0.6470695 ,
         -0.15757498, -0.35743886, -0.45743787,  0.05279505,  0.35000062],
        [ 0.22188234,  0.4412638 ,  0.39621222,  0.5085057 , -0.5456681 ,
          0.03971887,  0.11514938, -0.41593686,  0.54335535, -0.6277619 ],
        [ 0.09365833,  0.1739186 , -0.553138  ,  0.00362921,  0.61056566,
          0.1485725 , -0.10221785,  0.48424423, -0.2689283 ,  0.37256074]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.38854262],
        [ 0.22719389],
        [-0.5728252 ],
        [-0.18682122],
        [ 0.44491106],
        [ 0.16974986],
        [-0.7137544 ],
        [ 0.1319533 ],
        [-0.6893397 ],
        [ 0.32216197]], dtype=float32),
 array([0.], dtype=float32)]

In [55]:
model.get_weights()

[array([[-0.04747003,  0.5146726 ,  0.20851919, -0.1831721 ,  0.47569492,
          0.21864249,  0.09093289, -0.3133266 ,  0.4022554 ,  0.6876554 ],
        [-0.80920845, -0.3946289 ,  0.18929583,  0.31927902, -0.48960057,
         -0.05185237, -0.5298733 , -0.36113003, -0.06967221,  0.5730953 ],
        [ 0.66989976,  0.18382415,  0.67082566,  0.7788923 , -0.86467   ,
         -0.12829103,  0.56138104, -0.5938484 ,  0.6973534 , -1.1488606 ],
        [ 0.33288997,  0.00282296, -0.3569107 ,  0.14683968,  0.422521  ,
          0.03848193,  0.13169745,  0.37257782, -0.1392951 ,  0.08477037]],
       dtype=float32),
 array([ 0.14175703, -0.17194095, -0.20634317,  0.01856482, -0.1351019 ,
        -0.09355833,  0.11713421, -0.09258915, -0.1170514 ,  0.13954559],
       dtype=float32),
 array([[-0.6116533 ],
        [ 0.0948968 ],
        [-0.423447  ],
        [-0.18014012],
        [ 0.29485285],
        [ 0.09657589],
        [-0.9517531 ],
        [-0.01960994],
        [-0.60908735],
   

In [162]:
import copy

def discount_reward(orig_rewards, r):
    
    all_rewards = copy.deepcopy(orig_rewards)
    
    for rewards in all_rewards:
        for ind in range(len(rewards) - 2, -1, -1):
            rewards[ind] += rewards[ind+1]*r
    
    return all_rewards

def calculate_action_advantage(all_rewards, r):
    
    action_return = discount_reward(all_rewards, r)
    
    all_actions_return = np.concatenate([act for act in action_return])
    all_actions_mean = all_actions_return.mean()
    all_actions_std = all_actions_return.std()
    
    return [list((np.array(act) - all_actions_mean)/all_actions_std) for act in action_return]

In [163]:
# test discount reward
temp_rewards = [[10, 0, -50], [10,20,-60]]
discount_reward(temp_rewards, 0.9)

[[-30.5, -45.0, -50], [-20.6, -34.0, -60]]

In [164]:
print(temp_rewards)

[[10, 0, -50], [10, 20, -60]]


In [165]:
# test calculate action advantage
calculate_action_advantage([[10, 0, -50], [10,20,-60]], 0.9)

[[0.7271879509848277, -0.38078668536683635, -0.7628469047984446],
 [1.4836671854594121, 0.45974579738270194, -1.5269673436616613]]

In [69]:
obs = env.reset()

In [65]:
def play_one_step(env, model, obs, policy_grad = False):
    
    ## hard code policy
    
    with tf.GradientTape() as tape:
        proba = model(obs[np.newaxis])
        action = tf.cast(tf.random.uniform([1,1]) > proba, dtype=tf.int32)
        obs, reward, done, _ = env.step(action.numpy()[0][0])
        
        if not policy_grad:
            y_target = np.array([0] if obs[2] > 0 else [1])
        else:
            y_target = tf.cast(1 - action, dtype=tf.int32)
            
        loss = tf.reduce_mean(tf.metrics.binary_crossentropy(y_target, proba))
    
    grads = tape.gradient(loss, model.trainable_variables)
    
    return obs, reward, done, grads

In [68]:
obs, reward, done, grads = play_one_step(env, model, obs, True)

In [139]:
optimizer = keras.optimizers.Adam()

def play_episode(env, model, update_on_eps_end = True, max_iter = 100):
    
    done = False
    rewards = []
    obses = []
    frames = []
    grads = []
    
    obs = env.reset()
    iter_ = 0
    
    while not done and iter_ < max_iter:
        
        ## render img
        frames.append(env.render(mode='rgb_array'))
        
        obs, reward, done, grad = play_one_step(env, model, obs)
        
        if update_on_eps_end:
            optimizer.apply_gradients(zip(grads, model.trainable_variables))
        
        rewards.append(reward)
        obses.append(obs)
        grads.append(grad)
        
        iter_ += 1
    
    ## render final img
    frames.append(env.render(mode='rgb_array'))
        
    return rewards, obses, frames, grads

In [42]:
rewards, obses, frames, grads = play_episode(env, model)

In [47]:
def train_model(env, model, n_iter):
    
    all_frames = []
    all_obses = []
    all_rewards = []
    
    for i in range(n_iter):
        rewards, obses, frames, grads = play_episode(env, model)
        
        all_frames.append(frames)
        
    return all_rewards, all_obses, all_frames

In [60]:
all_rewards, all_obses, all_frames = train_model(env, model, 10)

In [61]:
for frames in all_frames:
    print(len(frames))

18
14
12
54
22
56
36
95
28
36


In [62]:
plot_animation(all_frames[7])

## Now, let's implement policy gradient

Policy gradient have 4 steps as follows:  
1. Play many episodes to get many of rewards and gradients for each episode. (Not yet update gradients) 
2. Calculate action's return using predefine discount factor  
3. Calculate action's advantage  
4. update gradient based on action's advantage value (element wise multiplication between action's advantage and gradient, then update the parameter using average gradient)

In [125]:
def cal_mean_grads(all_rewards, all_grads, discount_factor):
    
    action_advantage = calculate_action_advantage(all_rewards, discount_factor)
    flatten_grads = [[] for i in range(len(all_grads[0][0]))]
    
    for episode, grads in enumerate(all_grads):
        # grads of each episode
        for action, grad in enumerate(grads):
            # grad of each action
            for ind in range(len(grad)):
                grad[ind] = grad[ind]*action_advantage[episode][action]
                flatten_grads[ind].append(grad[ind])
    
#     print('flatten grads')
#     print(tf.shape(tf.stack(flatten_grads[1])))
#     print('test reduce mean')
#     print(tf.reduce_mean(tf.stack(flatten_grads[1]), axis = 0))
    
    return tf.reduce_mean(tf.stack(flatten_grads[1]), axis = 0)

In [132]:
keras.backend.clear_session()

In [143]:
def train_policy_grad(env, model, n_iter, n_episode, discount_factor = 0.9, optimizer = keras.optimizers.RMSprop()):

    for i in range(n_iter):
        
        all_frames = []
        all_obses = []
        all_rewards = []
        all_grads = []
        
        for num_eps in range(n_episode):
            rewards, obses, frames, grads = play_episode(env, model, update_on_eps_end = False, max_iter = 300)
            
            all_grads.append(grads)
            all_rewards.append(rewards)
            all_frames.append(frames)
            
        mean_grads = cal_mean_grads(all_rewards, all_grads, discount_factor)
        optimizer.apply_gradients(zip(mean_grads, model.trainable_variables))
        
    return all_frames, all_obses, all_rewards, all_grads

In [180]:
all_frames, all_obses, all_rewards, all_grads = train_policy_grad(env, model, 3, 20)

In [181]:
for ind, frames in enumerate(all_frames):
    print(f'round {ind} len frames {len(frames)}')

round 0 len frames 69
round 1 len frames 39
round 2 len frames 38
round 3 len frames 50
round 4 len frames 51
round 5 len frames 14
round 6 len frames 82
round 7 len frames 114
round 8 len frames 48
round 9 len frames 35
round 10 len frames 45
round 11 len frames 21
round 12 len frames 16
round 13 len frames 119
round 14 len frames 34
round 15 len frames 47
round 16 len frames 74
round 17 len frames 73
round 18 len frames 51
round 19 len frames 52


In [182]:
print(all_rewards[13])

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [183]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 61
Trainable params: 61
Non-trainable params: 0
_________________________________________________________________


In [184]:
plot_animation(all_frames[13])

In [ ]:

env = gym.make("CartPole-v1")
env.seed(42);

for iteration in range(n_iterations):
    all_rewards, all_grads = play_multiple_episodes(
        env, n_episodes_per_update, n_max_steps, model, loss_fn)
    total_rewards = sum(map(sum, all_rewards))                     # Not shown in the book
    print("\rIteration: {}, mean rewards: {:.1f}".format(          # Not shown
        iteration, total_rewards / n_episodes_per_update), end="") # Not shown
    all_final_rewards = discount_and_normalize_rewards(all_rewards,
                                                       discount_rate)
    all_mean_grads = []
    for var_index in range(len(model.trainable_variables)):
        mean_grads = tf.reduce_mean([final_reward * all_grads[episode_index][step][var_index]
             for episode_index, final_rewards in enumerate(all_final_rewards)
                 for step, final_reward in enumerate(final_rewards)], axis=0)
        all_mean_grads.append(mean_grads)
    optimizer.apply_gradients(zip(all_mean_grads, model.trainable_variables))

env.close()